### ISSUE TITLE
vcf to mmap files

### ISSUE THREAD

**Issue by elise625** [MMAP/MMAP-releases-issues-Q-and-A#2]
I have 22 exome chip vcf files that i need to convert so that i can run on mmap. Is there a way to do this?

**Comment by jeffoconnell496** [comment]
Hi - sorry for the delayed response.
There is a VCF converter implemented to handle sequence data. The default variant name is chr:pos or chr:pos:ref:alt. Is the rs# in your file? If so, do you prefer rs# as the variant name?
