### ISSUE TITLE
I got a "Segmentation fault (core dumped)" error

### ISSUE THREAD

**Issue by sharonxup6** [MMAP/MMAP-releases-issues-Q-and-A#5]
I'm running a GWAS with MMAP. I think I followed the instructions and it still doesn't work. The message shows "Segmentation fault (core dumped)." Where should I modify it? Thank you.
Here is my code:

cd ~/pathway/to/files/
/usr/local/MMAP/mmap \
--ped my_ped.bin \
--read_binary_covariance_file my_ped.bin \
--phenotype_filename my_phe.csv \
--trait ln_Ab \
--covariates AGE PC1 PC2 PC3 \
--gxe_interaction AGE \
--binary_covariate_filename ~/PROJ/GWAS/mmap_allchr.bin \
--binary_genotype_filename ~/PROJ/GWAS/mmap_allchr.bin \
--file_suffix ./output/ln_Ab

**Comment by jeffoconnell496** [comment]
The --gxe_interaction option is no longer supported in MMAP.
I suggest you consider GEM or LinGxEScanR

**Comment by sharonxup6** [comment]
I see. Thank you for your response and suggestions.

jeffoconnell496 ***@***.***> 於 2022年5月10日 週二 上午9:39寫道：
